const grammar = @import("../grammar.zig");

pub const spec = grammar.GrammarSpec{
    .name = "sql_core_ts",
    .parser_name = "SqlCoreGeneratedParser",
    .start_symbol = "stmt_list",
    .tokens = &.{
        .{ .name = "select" },
        .{ .name = "insert" },
        .{ .name = "delete" },
        .{ .name = "explain" },
        .{ .name = "bytecode" },
        .{ .name = "into" },
        .{ .name = "from" },
        .{ .name = "where" },
        .{ .name = "group" },
        .{ .name = "by" },
        .{ .name = "order" },
        .{ .name = "limit" },
        .{ .name = "offset" },
        .{ .name = "values" },
        .{ .name = "as" },
        .{ .name = "asc" },
        .{ .name = "desc" },
        .{ .name = "and" },
        .{ .name = "or" },
        .{ .name = "identifier" },
        .{ .name = "number" },
        .{ .name = "string" },
        .{ .name = "parameter" },
        .{ .name = "comma" },
        .{ .name = "period" },
        .{ .name = "equal" },
        .{ .name = "bang_equal" },
        .{ .name = "less" },
        .{ .name = "less_equal" },
        .{ .name = "greater" },
        .{ .name = "greater_equal" },
        .{ .name = "star" },
        .{ .name = "l_paren" },
        .{ .name = "r_paren" },
        .{ .name = "eof" },
    },
    .nonterminals = &.{
        "stmt_list",
        "stmt",
        "select_stmt",
        "insert_stmt",
        "delete_stmt",
        "source_ref",
        "qualified_name",
        "select_clauses",
        "projection_list",
        "projection",
        "expr",
        "expr_or",
        "expr_and",
        "expr_cmp",
        "primary",
        "expr_list",
        "where_clause",
        "group_clause",
        "order_clause",
        "order_list",
        "order_term",
        "limit_clause",
        "offset_clause",
    },
    .rules = &.{
        .{ .lhs = "stmt_list", .rhs = &.{ "stmt", "eof" }, .action = "emitComplete()", .condition = "enable_stmt_list_coverage" },
        .{ .lhs = "stmt", .rhs = &.{"select_stmt"}, .action = "emitStatement()" },
        .{ .lhs = "stmt", .rhs = &.{"insert_stmt"}, .action = "emitStatement()", .destructor = "destroyStatement()" },
        .{ .lhs = "stmt", .rhs = &.{"delete_stmt"}, .action = "emitStatement()", .destructor = "destroyStatement()" },
        .{ .lhs = "stmt", .rhs = &.{ "explain", "stmt" }, .action = "emitExplain()" },
        .{ .lhs = "stmt", .rhs = &.{ "explain", "bytecode", "stmt" }, .action = "emitExplainBytecode()" },
        .{ .lhs = "select_stmt", .rhs = &.{ "select", "projection_list" }, .action = "emitSelectConstant()" },
        .{ .lhs = "select_stmt", .rhs = &.{ "select", "projection_list", "from", "source_ref", "select_clauses" }, .action = "emitSelect()" },
        .{ .lhs = "insert_stmt", .rhs = &.{ "insert", "into", "qualified_name", "l_paren", "expr_list", "r_paren" }, .action = "emitInsert()" },
        .{ .lhs = "insert_stmt", .rhs = &.{ "insert", "into", "qualified_name", "l_paren", "expr_list", "r_paren", "values", "l_paren", "expr_list", "r_paren" }, .action = "emitInsertValues()" },
        .{ .lhs = "insert_stmt", .rhs = &.{ "insert", "into", "qualified_name", "values", "l_paren", "expr_list", "r_paren" }, .action = "emitInsertBareValues()" },
        .{ .lhs = "delete_stmt", .rhs = &.{ "delete", "from", "qualified_name", "where_clause" }, .action = "emitDelete()" },
        .{ .lhs = "source_ref", .rhs = &.{"qualified_name"}, .action = "emitSourceName()" },
        .{ .lhs = "source_ref", .rhs = &.{ "identifier", "l_paren", "number", "r_paren" }, .action = "emitSourceCall()" },
        .{ .lhs = "qualified_name", .rhs = &.{"identifier"}, .action = "emitQualifiedNameStart()" },
        .{ .lhs = "qualified_name", .rhs = &.{ "qualified_name", "period", "identifier" }, .action = "appendQualifiedName()" },
        .{ .lhs = "select_clauses", .rhs = &.{}, .action = "emitEmptyClauses()" },
        .{ .lhs = "select_clauses", .rhs = &.{"where_clause"}, .action = "attachWhere()" },
        .{ .lhs = "select_clauses", .rhs = &.{ "where_clause", "group_clause" }, .action = "attachGroup()" },
        .{ .lhs = "select_clauses", .rhs = &.{ "where_clause", "order_clause" }, .action = "attachOrder()" },
        .{ .lhs = "select_clauses", .rhs = &.{ "where_clause", "limit_clause" }, .action = "attachLimit()" },
        .{ .lhs = "select_clauses", .rhs = &.{ "where_clause", "group_clause", "order_clause" }, .action = "attachGroupOrder()" },
        .{ .lhs = "select_clauses", .rhs = &.{ "where_clause", "group_clause", "limit_clause" }, .action = "attachGroupLimit()" },
        .{ .lhs = "select_clauses", .rhs = &.{ "where_clause", "order_clause", "limit_clause" }, .action = "attachOrderLimit()" },
        .{ .lhs = "select_clauses", .rhs = &.{ "where_clause", "group_clause", "order_clause", "limit_clause" }, .action = "attachGroupOrderLimit()" },
        .{ .lhs = "select_clauses", .rhs = &.{"group_clause"}, .action = "attachGroup()" },
        .{ .lhs = "select_clauses", .rhs = &.{ "group_clause", "order_clause" }, .action = "attachGroupOrder()" },
        .{ .lhs = "select_clauses", .rhs = &.{ "group_clause", "limit_clause" }, .action = "attachGroupLimit()" },
        .{ .lhs = "select_clauses", .rhs = &.{ "group_clause", "order_clause", "limit_clause" }, .action = "attachGroupOrderLimit()" },
        .{ .lhs = "select_clauses", .rhs = &.{"order_clause"}, .action = "attachOrder()" },
        .{ .lhs = "select_clauses", .rhs = &.{ "order_clause", "limit_clause" }, .action = "attachOrderLimit()" },
        .{ .lhs = "select_clauses", .rhs = &.{"limit_clause"}, .action = "attachLimit()" },
        .{ .lhs = "projection_list", .rhs = &.{"projection"}, .action = "appendProjection()" },
        .{ .lhs = "projection_list", .rhs = &.{ "projection_list", "comma", "projection" }, .action = "appendProjection()" },
        .{ .lhs = "projection", .rhs = &.{"expr"}, .action = "emitProjection()" },
        .{ .lhs = "projection", .rhs = &.{ "expr", "as", "identifier" }, .action = "emitProjectionAlias()" },
        .{ .lhs = "projection", .rhs = &.{"star"}, .action = "emitStar()" },
        .{ .lhs = "expr", .rhs = &.{"expr_or"}, .action = "emitPrimaryExpr()" },
        .{ .lhs = "expr_or", .rhs = &.{"expr_and"}, .action = "emitPrimaryExpr()" },
        .{ .lhs = "expr_or", .rhs = &.{ "expr_or", "or", "expr_and" }, .action = "emitBinaryExpr()" },
        .{ .lhs = "expr_and", .rhs = &.{"expr_cmp"}, .action = "emitPrimaryExpr()" },
        .{ .lhs = "expr_and", .rhs = &.{ "expr_and", "and", "expr_cmp" }, .action = "emitBinaryExpr()" },
        .{ .lhs = "expr_cmp", .rhs = &.{"primary"}, .action = "emitPrimaryExpr()" },
        .{ .lhs = "expr_cmp", .rhs = &.{ "primary", "equal", "primary" }, .action = "emitBinaryExpr()" },
        .{ .lhs = "expr_cmp", .rhs = &.{ "primary", "bang_equal", "primary" }, .action = "emitBinaryExpr()" },
        .{ .lhs = "expr_cmp", .rhs = &.{ "primary", "less", "primary" }, .action = "emitBinaryExpr()" },
        .{ .lhs = "expr_cmp", .rhs = &.{ "primary", "less_equal", "primary" }, .action = "emitBinaryExpr()" },
        .{ .lhs = "expr_cmp", .rhs = &.{ "primary", "greater", "primary" }, .action = "emitBinaryExpr()" },
        .{ .lhs = "expr_cmp", .rhs = &.{ "primary", "greater_equal", "primary" }, .action = "emitBinaryExpr()" },
        .{ .lhs = "primary", .rhs = &.{"identifier"}, .action = "emitIdentifier()" },
        .{ .lhs = "primary", .rhs = &.{"number"}, .action = "emitNumber()" },
        .{ .lhs = "primary", .rhs = &.{"string"}, .action = "emitString()" },
        .{ .lhs = "primary", .rhs = &.{"parameter"}, .action = "emitParameter()" },
        .{ .lhs = "primary", .rhs = &.{ "l_paren", "expr", "r_paren" }, .action = "emitParenthesizedExpr()" },
        .{ .lhs = "primary", .rhs = &.{ "identifier", "l_paren", "expr_list", "r_paren" }, .action = "emitCall()" },
        .{ .lhs = "expr_list", .rhs = &.{"expr"}, .action = "appendExpr()" },
        .{ .lhs = "expr_list", .rhs = &.{ "expr_list", "comma", "expr" }, .action = "appendExpr()" },
        .{ .lhs = "where_clause", .rhs = &.{ "where", "expr" }, .action = "emitWhere()" },
        .{ .lhs = "group_clause", .rhs = &.{ "group", "by", "expr_list" }, .action = "emitGroup()" },
        .{ .lhs = "order_clause", .rhs = &.{ "order", "by", "order_list" }, .action = "emitOrder()" },
        .{ .lhs = "order_list", .rhs = &.{"order_term"}, .action = "appendOrder()" },
        .{ .lhs = "order_list", .rhs = &.{ "order_list", "comma", "order_term" }, .action = "appendOrder()" },
        .{ .lhs = "order_term", .rhs = &.{"expr"}, .action = "emitOrderTerm()" },
        .{ .lhs = "order_term", .rhs = &.{ "expr", "asc" }, .action = "emitOrderTermAsc()" },
        .{ .lhs = "order_term", .rhs = &.{ "expr", "desc" }, .action = "emitOrderTermDesc()" },
        .{ .lhs = "limit_clause", .rhs = &.{ "limit", "number" }, .action = "emitLimit()" },
        .{ .lhs = "limit_clause", .rhs = &.{ "limit", "number", "offset_clause" }, .action = "emitLimitOffset()" },
        .{ .lhs = "offset_clause", .rhs = &.{ "offset", "number" }, .action = "emitOffset()" },
    },
    .coverage_hook_name = "parsergen_coverage_sql_core_ts",
};
