const grammar = @import("../grammar.zig");

pub const spec = grammar.GrammarSpec{
    .name = "sql_core_ts",
    .parser_name = "SqlCoreGeneratedParser",
    .start_symbol = "stmt_list",
    .tokens = &.{
        .{ .name = "select" },
        .{ .name = "insert" },
        .{ .name = "delete" },
        .{ .name = "explain" },
        .{ .name = "bytecode" },
        .{ .name = "into" },
        .{ .name = "from" },
        .{ .name = "where" },
        .{ .name = "group" },
        .{ .name = "by" },
        .{ .name = "order" },
        .{ .name = "limit" },
        .{ .name = "offset" },
        .{ .name = "values" },
        .{ .name = "as" },
        .{ .name = "asc" },
        .{ .name = "desc" },
        .{ .name = "identifier" },
        .{ .name = "number" },
        .{ .name = "string" },
        .{ .name = "parameter" },
        .{ .name = "comma" },
        .{ .name = "equal" },
        .{ .name = "bang_equal" },
        .{ .name = "less" },
        .{ .name = "less_equal" },
        .{ .name = "greater" },
        .{ .name = "greater_equal" },
        .{ .name = "star" },
        .{ .name = "l_paren" },
        .{ .name = "r_paren" },
        .{ .name = "eof" },
    },
    .nonterminals = &.{
        "stmt_list",
        "stmt",
        "select_stmt",
        "insert_stmt",
        "delete_stmt",
        "projection_list",
        "projection",
        "expr",
        "expr_list",
        "where_clause",
        "group_clause",
        "order_clause",
        "limit_clause",
    },
    .rules = &.{
        .{ .lhs = "stmt_list", .rhs = &.{ "stmt", "eof" }, .action = "emitComplete()", .condition = "enable_stmt_list_coverage" },
        .{ .lhs = "stmt", .rhs = &.{"select_stmt"}, .action = "emitStatement()" },
        .{ .lhs = "stmt", .rhs = &.{"insert_stmt"}, .action = "emitStatement()", .destructor = "destroyStatement()" },
        .{ .lhs = "stmt", .rhs = &.{"delete_stmt"}, .action = "emitStatement()", .destructor = "destroyStatement()" },
        .{ .lhs = "stmt", .rhs = &.{ "explain", "stmt" }, .action = "emitExplain()" },
        .{ .lhs = "stmt", .rhs = &.{ "explain", "bytecode", "stmt" }, .action = "emitExplainBytecode()" },
        .{ .lhs = "select_stmt", .rhs = &.{ "select", "projection_list", "from", "identifier" }, .action = "emitSelect()" },
        .{ .lhs = "select_stmt", .rhs = &.{ "select", "projection_list", "from", "identifier", "where_clause" }, .action = "attachWhere()" },
        .{ .lhs = "insert_stmt", .rhs = &.{ "insert", "into", "identifier", "l_paren", "expr_list", "r_paren" }, .action = "emitInsert()" },
        .{ .lhs = "insert_stmt", .rhs = &.{ "insert", "into", "identifier", "l_paren", "expr_list", "r_paren", "values", "l_paren", "expr_list", "r_paren" }, .action = "emitInsertValues()" },
        .{ .lhs = "delete_stmt", .rhs = &.{ "delete", "from", "identifier", "where_clause" }, .action = "emitDelete()" },
        .{ .lhs = "projection_list", .rhs = &.{"projection"}, .action = "appendProjection()" },
        .{ .lhs = "projection_list", .rhs = &.{ "projection_list", "comma", "projection" }, .action = "appendProjection()" },
        .{ .lhs = "projection", .rhs = &.{"expr"}, .action = "emitProjection()" },
        .{ .lhs = "projection", .rhs = &.{"star"}, .action = "emitStar()" },
        .{ .lhs = "expr", .rhs = &.{"identifier"}, .action = "emitIdentifier()" },
        .{ .lhs = "expr", .rhs = &.{"number"}, .action = "emitNumber()" },
        .{ .lhs = "expr", .rhs = &.{"string"}, .action = "emitString()" },
        .{ .lhs = "expr", .rhs = &.{"parameter"}, .action = "emitParameter()" },
        .{ .lhs = "expr", .rhs = &.{ "identifier", "l_paren", "expr_list", "r_paren" }, .action = "emitCall()" },
        .{ .lhs = "expr_list", .rhs = &.{"expr"}, .action = "appendExpr()" },
        .{ .lhs = "expr_list", .rhs = &.{ "expr_list", "comma", "expr" }, .action = "appendExpr()" },
        .{ .lhs = "where_clause", .rhs = &.{ "where", "expr" }, .action = "emitWhere()" },
        .{ .lhs = "group_clause", .rhs = &.{ "group", "by", "expr_list" }, .action = "emitGroup()" },
        .{ .lhs = "order_clause", .rhs = &.{ "order", "by", "expr_list" }, .action = "emitOrder()" },
        .{ .lhs = "limit_clause", .rhs = &.{ "limit", "number" }, .action = "emitLimit()" },
    },
    .coverage_hook_name = "parsergen_coverage_sql_core_ts",
};
