const grammar = @import("../grammar.zig");

pub const spec = grammar.GrammarSpec{
    .name = "sydraql_core",
    .parser_name = "SydraqlGeneratedParser",
    .start_symbol = "stmt_list",
    .tokens = &.{
        .{ .name = "select" },
        .{ .name = "insert" },
        .{ .name = "delete" },
        .{ .name = "explain" },
        .{ .name = "bytecode" },
        .{ .name = "identifier" },
        .{ .name = "number" },
        .{ .name = "duration" },
        .{ .name = "string" },
        .{ .name = "timestamp" },
        .{ .name = "true" },
        .{ .name = "false" },
        .{ .name = "null" },
        .{ .name = "time", .fallback = "identifier" },
        .{ .name = "tag", .fallback = "identifier" },
        .{ .name = "from" },
        .{ .name = "where" },
        .{ .name = "group" },
        .{ .name = "by" },
        .{ .name = "fill" },
        .{ .name = "order" },
        .{ .name = "limit" },
        .{ .name = "offset" },
        .{ .name = "comma" },
        .{ .name = "l_paren" },
        .{ .name = "r_paren" },
        .{ .name = "eof" },
    },
    .nonterminals = &.{
        "stmt_list",
        "stmt",
        "select_stmt",
        "projection_list",
        "projection",
        "selector",
        "expr",
        "expr_list",
        "group_list",
        "order_list",
        "limit_clause",
    },
    .rules = &.{
        .{ .lhs = "stmt_list", .rhs = &.{ "stmt", "eof" }, .action = "emitComplete()", .condition = "enable_stmt_list_coverage" },
        .{ .lhs = "stmt", .rhs = &.{"select_stmt"}, .action = "emitStatement()" },
        .{ .lhs = "stmt", .rhs = &.{ "insert", "identifier" }, .action = "emitInsert()", .destructor = "destroyInsert()" },
        .{ .lhs = "stmt", .rhs = &.{ "delete", "identifier" }, .action = "emitDelete()", .destructor = "destroyDelete()" },
        .{ .lhs = "stmt", .rhs = &.{ "explain", "stmt" }, .action = "emitExplain()" },
        .{ .lhs = "stmt", .rhs = &.{ "explain", "bytecode", "stmt" }, .action = "emitExplainBytecode()" },
        .{ .lhs = "select_stmt", .rhs = &.{ "select", "projection_list" }, .action = "beginSelect()" },
        .{ .lhs = "select_stmt", .rhs = &.{ "select", "projection_list", "from", "selector" }, .action = "attachSelector()" },
        .{ .lhs = "select_stmt", .rhs = &.{ "select", "projection_list", "from", "selector", "where", "expr" }, .action = "attachPredicate()" },
        .{ .lhs = "projection_list", .rhs = &.{"projection"}, .action = "appendProjection()" },
        .{ .lhs = "projection_list", .rhs = &.{ "projection_list", "comma", "projection" }, .action = "appendProjection()" },
        .{ .lhs = "projection", .rhs = &.{"expr"}, .action = "emitProjection()" },
        .{ .lhs = "selector", .rhs = &.{"identifier"}, .action = "emitSelector()" },
        .{ .lhs = "selector", .rhs = &.{ "identifier", "l_paren", "number", "r_paren" }, .action = "emitByIdSelector()" },
        .{ .lhs = "expr", .rhs = &.{"identifier"}, .action = "emitIdentifier()" },
        .{ .lhs = "expr", .rhs = &.{"number"}, .action = "emitNumber()" },
        .{ .lhs = "expr", .rhs = &.{"duration"}, .action = "emitDuration()" },
        .{ .lhs = "expr", .rhs = &.{"string"}, .action = "emitString()" },
        .{ .lhs = "expr", .rhs = &.{"timestamp"}, .action = "emitTimestamp()" },
        .{ .lhs = "expr", .rhs = &.{"true"}, .action = "emitTrueLiteral()" },
        .{ .lhs = "expr", .rhs = &.{"false"}, .action = "emitFalseLiteral()" },
        .{ .lhs = "expr", .rhs = &.{"null"}, .action = "emitNullLiteral()" },
        .{ .lhs = "expr", .rhs = &.{ "identifier", "l_paren", "expr_list", "r_paren" }, .action = "emitCall()" },
        .{ .lhs = "expr_list", .rhs = &.{"expr"}, .action = "appendExpr()" },
        .{ .lhs = "expr_list", .rhs = &.{ "expr_list", "comma", "expr" }, .action = "appendExpr()" },
        .{ .lhs = "group_list", .rhs = &.{"expr"}, .action = "appendGroup()" },
        .{ .lhs = "order_list", .rhs = &.{"expr"}, .action = "appendOrder()" },
        .{ .lhs = "limit_clause", .rhs = &.{ "limit", "number" }, .action = "emitLimit()" },
    },
    .coverage_hook_name = "parsergen_coverage_sydraql_core",
};
