const std = @import("std");
const grammar = @import("grammar.zig");

pub const ParseArtifact = struct {
    grammar_name: []const u8,
    parser_name: []const u8,
    emitted_source: []u8,
    state_count_hint: usize,
    conflict_count_hint: usize,
    fallback_count: usize,
};

pub const ParserGenerator = struct {
    allocator: std.mem.Allocator,

    pub fn init(allocator: std.mem.Allocator) ParserGenerator {
        return .{ .allocator = allocator };
    }

    pub fn emit(self: *ParserGenerator, spec: grammar.GrammarSpec) !ParseArtifact {
        var out = std.array_list.Managed(u8).init(self.allocator);
        errdefer out.deinit();

        const writer = out.writer();
        try writer.print("// generated by sydra parsergen for {s}\n", .{spec.name});
        try writer.writeAll("const std = @import(\"std\");\n");
        try writer.writeAll("pub const ParserMetadata = struct {\n");
        try writer.writeAll("    pub const grammar_name = ");
        try writeQuoted(writer, spec.name);
        try writer.writeAll(";\n");
        try writer.writeAll("    pub const parser_name = ");
        try writeQuoted(writer, spec.parser_name);
        try writer.writeAll(";\n");
        try writer.writeAll("    pub const start_symbol = ");
        try writeQuoted(writer, spec.start_symbol);
        try writer.writeAll(";\n");
        try writer.writeAll("};\n\n");

        try writer.writeAll("pub const tokens = [_][]const u8{\n");
        var fallback_count: usize = 0;
        for (spec.tokens) |token| {
            try writer.writeAll("    ");
            try writeQuoted(writer, token.name);
            try writer.writeAll(",\n");
            if (token.fallback != null) fallback_count += 1;
        }
        try writer.writeAll("};\n\n");

        try writer.writeAll("pub const fallbacks = [_]struct { token: []const u8, fallback: []const u8 }{\n");
        for (spec.tokens) |token| {
            if (token.fallback) |fallback| {
                try writer.writeAll("    .{ .token = ");
                try writeQuoted(writer, token.name);
                try writer.writeAll(", .fallback = ");
                try writeQuoted(writer, fallback);
                try writer.writeAll(" },\n");
            }
        }
        try writer.writeAll("};\n\n");

        try writer.writeAll("pub const nonterminals = [_][]const u8{\n");
        for (spec.nonterminals) |symbol| {
            try writer.writeAll("    ");
            try writeQuoted(writer, symbol);
            try writer.writeAll(",\n");
        }
        try writer.writeAll("};\n\n");

        try writer.writeAll("pub const rules = [_]struct { lhs: []const u8, rhs_len: usize, conditional: bool, has_destructor: bool }{\n");
        for (spec.rules) |rule| {
            try writer.writeAll("    .{ .lhs = ");
            try writeQuoted(writer, rule.lhs);
            try writer.print(", .rhs_len = {d}, .conditional = {}, .has_destructor = {} }},\n", .{
                rule.rhs.len,
                rule.condition != null,
                rule.destructor != null,
            });
        }
        try writer.writeAll("};\n");

        if (spec.coverage_hook_name) |hook| {
            try writer.writeAll("\npub const coverage_hook_name = ");
            try writeQuoted(writer, hook);
            try writer.writeAll(";\n");
        }

        return .{
            .grammar_name = spec.name,
            .parser_name = spec.parser_name,
            .emitted_source = try out.toOwnedSlice(),
            .state_count_hint = estimateStates(spec),
            .conflict_count_hint = 0,
            .fallback_count = fallback_count,
        };
    }
};

fn writeQuoted(writer: anytype, value: []const u8) !void {
    try writer.print("\"{s}\"", .{std.zig.fmtEscapes(value)});
}

fn estimateStates(spec: grammar.GrammarSpec) usize {
    return spec.rules.len + spec.nonterminals.len + spec.tokens.len;
}

test "parser generator emits lemon-style metadata skeleton" {
    const alloc = std.testing.allocator;
    const sydraql = @import("grammars/sydraql_core.zig").spec;
    var gen = ParserGenerator.init(alloc);
    const artifact = try gen.emit(sydraql);
    defer alloc.free(artifact.emitted_source);

    try std.testing.expectEqualStrings("sydraql_core", artifact.grammar_name);
    try std.testing.expectEqualStrings("SydraqlGeneratedParser", artifact.parser_name);
    try std.testing.expect(artifact.state_count_hint >= sydraql.rules.len);
    try std.testing.expect(artifact.fallback_count != 0);
    try std.testing.expect(std.mem.indexOf(u8, artifact.emitted_source, "pub const fallbacks") != null);
    try std.testing.expect(std.mem.indexOf(u8, artifact.emitted_source, "coverage_hook_name") != null);
}

test "parser generator handles SQL core grammar skeleton" {
    const alloc = std.testing.allocator;
    const sql_core = @import("grammars/sql_core_ts.zig").spec;
    var gen = ParserGenerator.init(alloc);
    const artifact = try gen.emit(sql_core);
    defer alloc.free(artifact.emitted_source);

    try std.testing.expectEqualStrings("sql_core_ts", artifact.grammar_name);
    try std.testing.expectEqualStrings("SqlCoreGeneratedParser", artifact.parser_name);
    try std.testing.expect(std.mem.indexOf(u8, artifact.emitted_source, "\"select\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, artifact.emitted_source, "\"stmt_list\"") != null);
}
